name: Schedule Test

on:
  schedule: ## Schedule the job to run at 12.am daily.
    - cron: '* * * * *'

jobs:
  Check-Repo-Code:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: cat app.py
        run: cat app.py

  Echo-text:
    needs: [Check-Repo-Code]
    runs-on: 'ubuntu-latest'
    steps:
      - name: Echo Finish
        run: echo "🍏 This job's status is ${{ job.status }}."


    